config/routes.rb
Together::Application.routes.draw do
  resources :subscribers do
    get 'notify_all', :on => :collection
  end

  get "welcome/home"

  root :to => 'welcome#home'

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates :email, :presence => true, :uniqueness => true, :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

   def authenticate_admin_access
		authenticate_or_request_with_http_basic do |username, password|
			username == "together" and password == "togeTher"
		end
	end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_filter :authenticate_admin_access
  layout 'welcome'
  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscribers }
    end
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/new
  # GET /subscribers/new.json
  def new
    @subscriber = Subscriber.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/1/edit
  def edit
    @subscriber = Subscriber.find(params[:id])
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(params[:subscriber])
      if @subscriber.save
         UserMailer.subscribing_user(@subscriber).deliver
        respond_to do |f|
          f.js
        end
    end
  end

  # PUT /subscribers/1
  # PUT /subscribers/1.json
  def update
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      if @subscriber.update_attributes(params[:subscriber])
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :ok }
    end
  end

  def notify_all
    @subscribers = Subscriber.all
    @subscribers.each do |user|
         UserMailer.notify_all_user(user).deliver
    end
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'

  def home
    @subscriber  = Subscriber.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Together</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Together</title>
  <%= stylesheet_link_tag "bootstrap", "style" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-together">
  <%= yield %>
</div>
</body>
</html>

app/views/subscribers/_form.html.erb
<%= form_for(@subscriber) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscribers/create.js.erb
<% if @subscriber.errors.any? -%>
$("#ajax_spinner").hide();
$(".error").show();
$(":input:not(input[type=submit])").val("");
<% else -%>
document.getElementById('light').style.display = 'block';document.getElementById('fade').style.display = 'block';
$("#ajax_spinner").hide(300);
$("#notice").show(300);
$(":input:not(input[type=submit])").val("");
<% end -%>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<h1>Listing subscribers</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Action</th>
  </tr>

<% @subscribers.each do |subscriber| %>
  <tr>
    <td><%= subscriber.email %></td>
    <td><%= link_to 'Destroy', subscriber, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Home', root_path %><br />
<%= link_to 'New Subscriber', root_path %><br />
<%= link_to 'Send Launching News To All!', notify_all_subscribers_path  %>

app/views/subscribers/new.html.erb
<h1>New subscriber</h1>

<%= render 'form' %>

<%= link_to 'Back', subscribers_path %>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @subscriber.email %>
</p>


<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>

app/views/welcome/home.html.erb
<div class="row error" style="display: none;">
  <p style="font-size: 20px; color: #fefefe; background-color: #ff0000; line-height: 35px; text-align: center;  -moz-border-radius: 8px;
          -ms-border-radius: 8px;
          -o-border-radius: 8px;
          -webkit-border-radius: 8px; ">Please provide valid email address</p>
   <div class="clear1"></div>
</div>

<div id="notice">
  <div id="light" class="white_content">
    <div class="user-notice">
      <div class="clear1"></div>
      <p style="font-size: 20px; text-align: center; line-height: 30px">Thank you for subscribing, an email has been sent to your email
        address</p>

      <div class="clear1"></div>
      <p style="font-size: 20px; text-align: center; "><a href="#" class="btn" id="ok-lb">Ok</a></p>
    </div>
  </div>
  <div id="fade" class="black_overlay"></div>
</div>

<p style="font-size: 30px; text-align: center;"><a class="TogetherText" href="/">Together.</a></p>

<p style="font-size: 20px"> Description of service.</p>
<h5>Please subscribe your email address, we will confirm you soon we launch our site </h5>
<div class="clear1"></div>
<%= image_tag('ajax_spinner.gif', :id => 'ajax_spinner', :style => 'display: none') %>
<div class="clear1"></div>
<div class="email-form">
  <%= form_for(@subscriber, :remote => true) do |f| %>
      <%= f.label :email, :class => 'label warning', :style => "height: 24px;" %> &nbsp; &nbsp;
      <%= f.text_field :email, :class => 'xlarge' %>
      <br/>

      <div class="clear1"></div>
      <div class="submit-button-box">
        <%= f.submit 'Subscribe', :disable_with => 'Subscribing..', :class => 'btn' %>
      </div>
  <% end %>
</div>

<div class="footer" style="margin-top: 60px; text-align: center;">Copyright &copy; 2012 Together, Inc.
  All rights reserved.
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("a#ok-lb").click(function() {
            document.getElementById('light').style.display = 'none';
            document.getElementById('fade').style.display = 'none';
        });
    });
</script>

<script type="text/javascript">
    $('#new_subscriber').submit(function() {
        $('#ajax_spinner').show();
    });
</script>